import Header from "./components/Header";
import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";



export const metadata: Metadata = {
  title: "ShoeDop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-179594776657147"
          crossOrigin="anonymous"
        ></Script>
      </head>
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
